//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Difi.SikkerDigitalPost.Klient.Tester.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("hjarvald.tuftKUK#0BNU")]
        public string DigitalPostkasseAdresseMottaker {
            get {
                return ((string)(this["DigitalPostkasseAdresseMottaker"]));
            }
            set {
                this["DigitalPostkasseAdresseMottaker"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("04036125433")]
        public string PersonnummerMottaker {
            get {
                return ((string)(this["PersonnummerMottaker"]));
            }
            set {
                this["PersonnummerMottaker"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("984661185")]
        public string OrganisasjonsnummerAvsender {
            get {
                return ((string)(this["OrganisasjonsnummerAvsender"]));
            }
            set {
                this["OrganisasjonsnummerAvsender"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("984661185")]
        public string OrganisasjonsnummerPostkasse {
            get {
                return ((string)(this["OrganisasjonsnummerPostkasse"]));
            }
            set {
                this["OrganisasjonsnummerPostkasse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://qaoffentlig.meldingsformidler.digipost.no/api/ebms")]
        public string UrlMeldingsformidler {
            get {
                return ((string)(this["UrlMeldingsformidler"]));
            }
            set {
                this["UrlMeldingsformidler"] = value;
            }
        }
    }
}
