//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Difi.SikkerDigitalPost.Klient.Testklient.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("04036125433")]
        public string DigipostMottakerPersonnummer {
            get {
                return ((string)(this["DigipostMottakerPersonnummer"]));
            }
            set {
                this["DigipostMottakerPersonnummer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ove.jonsen#6K5A")]
        public string DigipostMottakerDigipostadresse {
            get {
                return ((string)(this["DigipostMottakerDigipostadresse"]));
            }
            set {
                this["DigipostMottakerDigipostadresse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("984661185")]
        public string PostenOrgNr {
            get {
                return ((string)(this["PostenOrgNr"]));
            }
            set {
                this["PostenOrgNr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8702F5E55217EC88CF2CCBADAC290BB4312594AC")]
        public string DatabehandlerSertifikatThumbprint {
            get {
                return ((string)(this["DatabehandlerSertifikatThumbprint"]));
            }
            set {
                this["DatabehandlerSertifikatThumbprint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("991825827")]
        public string DifiOrgNummer {
            get {
                return ((string)(this["DifiOrgNummer"]));
            }
            set {
                this["DifiOrgNummer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("b0cb922214d11e8ce993838db4c6d04c0c0970b8")]
        public string DifiSertifikatThumbprint {
            get {
                return ((string)(this["DifiSertifikatThumbprint"]));
            }
            set {
                this["DifiSertifikatThumbprint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("02118449641")]
        public string EboksMottakerPersonnummer {
            get {
                return ((string)(this["EboksMottakerPersonnummer"]));
            }
            set {
                this["EboksMottakerPersonnummer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0000167396")]
        public string EboksMottakerEboksadresse {
            get {
                return ((string)(this["EboksMottakerEboksadresse"]));
            }
            set {
                this["EboksMottakerEboksadresse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("984661185")]
        public string DigipostOrgNr {
            get {
                return ((string)(this["DigipostOrgNr"]));
            }
            set {
                this["DigipostOrgNr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("996460320")]
        public string EboksOrgNr {
            get {
                return ((string)(this["EboksOrgNr"]));
            }
            set {
                this["EboksOrgNr"] = value;
            }
        }
    }
}
